# Artificial Neural Network

In [6]:
# Developed multi-layered ANN model and fine-tuned hyperparameters for optimal performance

### Importing the libraries

In [7]:
import numpy as np  # Import the NumPy library for numerical operations.
import pandas as pd  # Import the Pandas library for data manipulation and analysis.
import tensorflow as tf  # Import TensorFlow, an open-source machine learning framework.

In [8]:
tf.__version__  # Display the version of TensorFlow being used.

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [9]:

# Load the dataset from a CSV file named 'Churn_data.csv' using Pandas.
dataset = pd.read_csv('Churn_data.csv')

# Extract the feature variables (X) and the target variable (y) from the dataset.
# We use iloc to slice the dataset, selecting columns from the 4th to the second-to-last column for X.
X = dataset.iloc[:, 3:-1].values

# We use iloc to select the last column as the target variable (y).
y = dataset.iloc[:, -1].values

In [10]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [11]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [12]:
from sklearn.preprocessing import LabelEncoder  # Import LabelEncoder from scikit-learn for categorical data encoding.

le = LabelEncoder()  # Create a LabelEncoder object to encode categorical data.

# Apply LabelEncoder to the third column (index 2) of the feature matrix X.
X[:, 2] = le.fit_transform(X[:, 2])


In [13]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [14]:
from sklearn.compose import ColumnTransformer  # Import ColumnTransformer from scikit-learn for column-wise transformations.
from sklearn.preprocessing import OneHotEncoder  # Import OneHotEncoder from scikit-learn for one-hot encoding.

ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [1])],  # Apply OneHotEncoder to the second column (index 1).
    remainder='passthrough'  # Keep the remaining columns unchanged.
)

# Apply the ColumnTransformer to the feature matrix X and convert it to a NumPy array.
X = np.array(ct.fit_transform(X))


In [15]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [16]:
from sklearn.model_selection import train_test_split  # Import train_test_split from scikit-learn for dataset splitting.

# Split the dataset into training and testing sets.
# X_train: Training features, X_test: Testing features
# y_train: Corresponding labels for training, y_test: Corresponding labels for testing
# test_size specifies the proportion of data to be used for testing (here, 20%).
# random_state ensures reproducibility of the split.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


### Feature Scaling

In [17]:
from sklearn.preprocessing import StandardScaler  # Import StandardScaler from scikit-learn for feature scaling.

sc = StandardScaler()  # Create a StandardScaler object for feature scaling.

# Fit the StandardScaler on the training data and transform the training features.
X_train = sc.fit_transform(X_train)

# Transform the testing features using the same scaling parameters as the training data.
X_test = sc.transform(X_test)


## Part 2 - Building the ANN

### Initializing the ANN

In [18]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [20]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [21]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [22]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [23]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 3s 2ms/step - loss: 0.5428 - accuracy: 0.7663
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4610 - accuracy: 0.7969
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4377 - accuracy: 0.8039
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4249 - accuracy: 0.8081
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4151 - accuracy: 0.8126
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4062 - accuracy: 0.8192
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3971 - accuracy: 0.8215
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3877 - accuracy: 0.8344
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3786 - accuracy: 0.8403
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3707 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Solution**

In [24]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 121ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [25]:
# Predict churn using the trained neural network model 'ann' on the testing data.
y_pred = ann.predict(X_test)

# Convert the predicted probabilities into binary predictions using a threshold of 0.5.
y_pred = (y_pred > 0.5)

# Concatenate the predicted churn results and the actual labels for comparison.
comparison_result = np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis=1)

print(comparison_result)

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score  # Import necessary metrics from scikit-learn.

# Calculate the confusion matrix to evaluate the performance of the model.
cm = confusion_matrix(y_test, y_pred)

# Print the confusion matrix.
print(cm)

# Calculate and print the accuracy score of the model.
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


[[1504   91]
 [ 189  216]]
Accuracy: 0.86
